### ISSUE TITLE
User diagram

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#10]
- [x] 1. Xác định actor
- [x] 2. Xác định các use case
- [x] 3. Mối liên hệ giữa actor và use case
- [x] 4. Mối liên hệ giữa use case và use case
- [x] 5. Mối liên hệ giữa actor và acctor
- [x] 6. Lưu ý khi vẽ use case diagram
- [x] 7. Vẽ use case diagram

**Comment by CTminhduc** [comment]
21/03 - hoàn thành task 1 
https://docs.google.com/document/d/1okjAjBXjXVaFuP3TNou57M2rJEVbOpGv9J3-XE68ETE/edit?usp=sharing

**Comment by CTminhduc** [comment]
22/03 - hoàn thành task 2
https://docs.google.com/document/d/14sTPaY5FvvgNY8ffm1PmRP6Dp-ZTrL5BQPdsZYmnsZ4/edit?usp=sharing

**Comment by CTminhduc** [comment]
23/03 - hoàn thành task 3
https://docs.google.com/document/d/1LrX_4lgqyX2ZPYHaHKGef6dMAxzLg8gkfR2SiMfXEFA/edit?usp=sharing

**Comment by CTminhduc** [comment]
24/03 - hoàn thành task 4
https://docs.google.com/document/d/1SyynF6drbdkBUQOBDqAq1zAvSOdfQjJyIzQLwjLbYVI/edit?usp=sharing

**Comment by CTminhduc** [comment]
25/03 - hoàn thành task 5
https://docs.google.com/document/d/16zvqFdRXyiFiyTWx5vnKf38txZpScYjM0jpoYCO7WPM/edit?usp=sharing

**Comment by CTminhduc** [comment]
26/03 - hoàn thành task 6
https://docs.google.com/document/d/13FmgzrCOrNspUlCkTDzoQKV3JwyZ4curexzZGJ9boy4/edit?usp=sharing

**Comment by CTminhduc** [comment]
27/03 - hoàn thành task 7
https://docs.google.com/document/d/1yYsCQORhDLYXv1sBSlXI8H_gNsUbocz4z5X9PoxjNfw/edit?usp=sharing
