### ISSUE TITLE
Đặc tả use case diagram(Mô tả lại UI)

### ISSUE THREAD

**Issue by CTminhduc** [LuongXuanThang20110724/Web_TalkDesk#15]
- [x] 1. Đặc tả chức năng đăng nhập
- [x] 2. Đặc tả chức năng đăng ký
- [x] 3. Đặc tả chức năng đăng xuất
- [x] 4. Đặc tả chức năng quên mật khẩu
- [x] 5. Đặc tả chức năng theo dõi các số liệu lịch sử 
- [x] 6. Đặc tả chức năng xem phản hồi, đánh giá
- [x] 7. Đặc tả chức năng theo dõi trạng thái khách hàng
- [x] 8. Đặc tả chức năng thêm trạng thái khách hàng
- [x] 9.  Đặc tả chức năng xóa trạng thái khách hàng
- [x] 10.  Đặc tả chức năng sửa trạng thái khách hàng
- [x] 11.  Đặc tả chức năng phân tích tương tác khách hàng

**Comment by quyenthieucanxi** [comment]
29/03/2023 - 01/4/2023 Hoàn thành task 1 đến task 4
https://docs.google.com/document/d/1v7bil5YGucTaYfJ7EwjOuEj-iJDvmGBQ3_PizSImyV0/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
02/04/2023 Hoàn thành task 5
https://docs.google.com/document/d/12XZDitc2vcxmalaScZodsiVmYBj9PmVRH4in_wRMSC0/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
03/04/2023 Hoàn thành task 6
https://docs.google.com/document/d/1QiY7E-RE7LDQT-ygN43kcNmDGr49os90ib9-ptaFCFM/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
03/04/2023 Hoàn thành task 7
https://docs.google.com/document/d/13S31bXXLDvcAMPOY0xFKR8bmy7gOHEDySWU12k_jn7M/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
03/04/2023 Hoàn thành task 8
https://docs.google.com/document/d/1sZI-p4XcvVPrdnG_oPBzYux5PPiowSbcWt5Vz8lOR3s/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
03/04/2023 Hoàn thành task 9 và task 10
https://docs.google.com/document/d/1ZbSLRmt8BKxXIG4B73FHVfkObzAR6LsNJXj9nvCdgJA/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
03/04/2023 Hoàn thành task 11
https://docs.google.com/document/d/1lRVM0xvRQMWSVvVwZZT_c81hQqaPXqb1UrjiWoVMUtI/edit?usp=sharing
