### ISSUE TITLE
Code UI "ServiceLevel"

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#20]
- [x] 1. Sử dụng và tinh chỉnh lại component Feature2
- [x] 2. Sử dụng và tinh chỉnh lại select "filter"
- [x] 3. Sử dụng và tinh chỉnh lại "Times"
- [x] 4. Sử dụng và tinh chỉnh lại "Stacked Bar Chart"
- [x] 5. Code "Pie Chart With Needle"
- [x] 6. Review hoàn chỉnh

**Comment by CTminhduc** [comment]
Hoàn thành task 1
https://docs.google.com/document/d/1oORB2ic_fwMOneiMZIFrrTgubUf3vahSnOEpDT1EHgA/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 2
https://docs.google.com/document/d/18vaY1PAKJOoUzpze1Mks_kzM4Qs_UuMY8uAiRarKpmA/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 3
https://docs.google.com/document/d/1SzUjRR3QXbOYkeV2aA4scMztQiuz777TSURfUZk4SW4/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 4
https://docs.google.com/document/d/14o6_SzTYUGmUMoUG77UDaKB5D3fCLkI3hlC4kPYrYjU/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 5
https://docs.google.com/document/d/1LYKy3LSxOQps-FuKH4XMhn5tDtEb2_GKhtlD5F2O2k8/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 6
https://docs.google.com/document/d/1qAd-WNgm7wlLP9sHUdifMfq189oQptqnpaw7ygFSTnY/edit?usp=sharing
