### ISSUE TITLE
Code UI "Agents"

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#21]
- [x]  1. Sử dụng và tinh chỉnh lại component Feature2
- [x]  2. Sử dụng và tinh chỉnh lại select "filter"
- [x]  3. Sử dụng và tinh chỉnh lại "Stacked Bar Chart"
- [x]  4. Code "status of Agents"

**Comment by CTminhduc** [comment]
Hoàn thành task: Sử dụng và tinh chỉnh lại component Feature2
https://docs.google.com/document/d/1g04aJLkDZ_cm9maW02-0UI92K2GVe20Dmd24uwUbffc/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
07/04/2023 Hoàn thành task 2
https://docs.google.com/document/d/1h5Jepe_I5Y9GdhXGFYoLal3oaEbnLYmWWRVGzQeUI4s/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
08/04/2023 Hoàn thành task 3
https://docs.google.com/document/d/1tpSGUsih6F-sGFsBbXotDvxyMt2Qk9QRvjSk3WcMXSU/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
09/04/2023 Hoàn thành task 4
https://docs.google.com/document/d/1Wi7y5QM5SwObX0AVG--XMBv6N5tZFFZR_vma2XVqk-E/edit?usp=sharing
