### ISSUE TITLE
Code UI "Numbers"

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#22]
- [x]  1. Code component Feature2
- [x]  2. Code lại select "filter"
- [x]  3. Code "Stacked Bar Chart"
- [x]  4. Code "phone number"

**Comment by quyenthieucanxi** [comment]
04/04/2023 Hoàn thành task1 
https://docs.google.com/document/d/1fUqTMP_ZeenT0vm90W9_wSeVL9-e_BejcXr_fixz_qM/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
05/04/2023 Hoàn thành task 2
https://docs.google.com/document/d/17mbM1A_zi-zmiALq9CKPAXcKrIeT44JYWDU-rZlRfGk/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
06/04/2023 Hoàn thành task 3
https://docs.google.com/document/d/1zp9qWjsf2p6P3x4vdPwp39-zD-gFSjdYS0NFsHJjPn8/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
07/04/2023 Hoàn thành task 4
https://docs.google.com/document/d/1nvzLqSJHjgzVXL8U51yfHNsVi1e_-C_r8-_RDi9KSTM/edit?usp=sharing
