### ISSUE TITLE
Deploy lên AWS

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#23]
- [x] 1. Tạo tài khoản AWS
- [x] 2. Cài đặt docker
- [x] 3. Taọ Dockerfile cho React-app
- [x] 4. Tạo folder cấu hình nginx
- [x] 5. Build docker container
- [x] 6. Build docker image
- [x] 7. Cài đặt AWS CLI tools
- [x] 8.Tạo Elastic Container Registry (ECR)
- [x] 9. Push docker image lên Cloud

**Comment by quyenthieucanxi** [comment]
Hoàn thành task 1 
https://docs.google.com/document/d/1somjSH_7EaKBF9lmY4rTOaLQggAmsgk5b1tJfyK9NbM/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
Hoàn thành task 2
https://docs.google.com/document/d/1GzLFcANMtCgJTAESsn73YWJ8PsjABgUVN5UoWGUrpmQ/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
Hoàn thành task 3
https://docs.google.com/document/d/1eb3cIQKhoW2O4BZKvhNiwVevynemWeUIB3HdxS_Y74g/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
Hoàn thành task 4 
https://docs.google.com/document/d/1LG1NBblax_ssQX5NW-MU6CF9EeyZxieM-3esrnANkd0/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
Hoàn thành task 5 và task 6
https://docs.google.com/document/d/1M85HLQG_wbdHz-vmdm2oC60mBGWQO4muK8Cy0YXWRtU/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
Hoàn thành task 7 
https://docs.google.com/document/d/1esRVhPJNFbM1E9G1FfFQWbCsk93gcqvTN0GNskeQJCY/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
Hoàn thành task 8
https://docs.google.com/document/d/1L_zamg_eY4c1S3l_2WSG6bg6VabVPI5K2CmthZPhnMw/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
Hoàn thành task 9
https://docs.google.com/document/d/1iygwDhJeMLqOu9aeXG0qfZODp0w7l6T28m8KTG1P4IE/edit?usp=sharing
