### ISSUE TITLE
Tạo CI/CD (circle CI)

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#24]
- [x] 1. Khái niệm, công dụng của cricle CI
- [x] 2. Cách hoạt động của cricle CI
- [x] 3. Những lưu ý khi sử dụng cricle CI
- [x] 4. Cài đặt cricle Cl
- [x] 5. Cấu hình cho project
- [x] 6. Cấu hình cho cricle CI
- [x] 7. Hoàn tất Build CI/CD

**Comment by CTminhduc** [comment]
Hoàn thành task 1:
https://docs.google.com/document/d/1ewvt00d_TL0Sc2RJxRL-esFnZTf_maUv_TlsXq9r03s/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 2:
https://docs.google.com/document/d/1UZ5inhIV3NrQHkoJsv9vDGlfaMcx0CaVh9BanblH_qQ/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 3:
https://docs.google.com/document/d/1uL4R8Dkhw7sKyQnVFeu7GPI2XO2VkdbR8eFWMLQO6Co/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 4:
https://docs.google.com/document/d/1a4MF7s82k7uWFgtH88XzMfT-NtlAABheNyDdQBxb_IU/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 5:
https://docs.google.com/document/d/1uqBCTWAYKd18-UAuUBRYDfRV_JJnNw8Oc4iRfK1V2o8/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 6:
https://docs.google.com/document/d/1uFxFunGAdKeXHdQ7RQRXsMGrLCd5qO9HvgHrKZalbJ8/edit?usp=sharing

**Comment by CTminhduc** [comment]
Hoàn thành task 7:
https://docs.google.com/document/d/15kQQwzF-oYTsnJlES3wEyMOmzZ1w0JnUPSv4iU_4eL0/edit?usp=sharing
