### ISSUE TITLE
Tìm hiểu cấu trúc giao diện trang web

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#3]
- [x] 1. Phần header, footer
- [x] 2. Phần content area
- [x] 3. Phần liên hệ qua chat box, các khối nội dung

**Comment by CTminhduc** [comment]
Hoàn thành task1 
[Task1.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/10986265/Task1.docx)

**Comment by CTminhduc** [comment]
Hoàn thành task 2-3
[Task2-3.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/10989626/Task2-3.docx)
