### ISSUE TITLE
Chuẩn bị các thành phần cho css của trang web

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#4]
- [x] 1. Xác định các Font Text của website
- [x] 2. Xác định Color Text của Website
- [x] 3. Xác định kích thước Text của Website
- [x] 4. Xác định màu sắc website
- [x] 5.Kiểm tra kích thước các yếu tố trên thiết kế.
- [x] 6. Xác định các Components

**Comment by quyenthieucanxi** [comment]
Hoàn thành Task 1, Task 2 và Task 3
[Task1-3.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/11004002/Task1-3.docx)

**Comment by CTminhduc** [comment]
Hoàn thành Task 4
[Task4.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/11007599/Task4.docx)

**Comment by CTminhduc** [comment]
Hoàn thành Task 5
[Task5.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/11008914/Task5.docx)

**Comment by quyenthieucanxi** [comment]
Hoàn thành Task 6
[Task 6.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/11009226/Task.6.docx)
