### ISSUE TITLE
Chuẩn bị hình ảnh và icon cho trang web

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#6]
- [x] 1. Xác định các hình ảnh ở Website
- [x] 2. Xác định  các icon  của Website
- [x] 3. Thêm thư mục ảnh vào cấu trúc Frond end (Sau khi đã có cấu trúc thư mục Frond end)

**Comment by quyenthieucanxi** [comment]
Hoàn thành task1 và task 2
[Task1-2.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/10986454/Task1-2.docx)

**Comment by quyenthieucanxi** [comment]
Hoàn thành task 3
[Task3.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/11008950/Task3.docx)
