### ISSUE TITLE
Cấu trúc BackEnd (Nodejs)

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#7]
- [x] 1. Tạo project NodeJs
- [x] 2. Tải các thư viện cần thiết
- [x] 3. Cấu trúc lại các thư mục của project-backend
- [x] 4. Tạo và kết nối database, sử dụng database MongoDB

**Comment by LuongXuanThang20110724** [comment]
hoàn thành 4 task.
[Task2.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/11008602/Task2.docx)

**Comment by LuongXuanThang20110724** [comment]
hoàn thành task 4.
[task4.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/11008679/task4.docx)

**Comment by CTminhduc** [comment]
Hoàn thành task 1-2
[Task1-2.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/11008924/Task1-2.docx)

**Comment by LuongXuanThang20110724** [comment]
hoàn thành task 3.
[task3.docx](https://github.com/LuongXuanThang20110724/Web_TalkDesk/files/11009032/task3.docx)
