### ISSUE TITLE
Đặc tả usercase

### ISSUE THREAD

**Issue by LuongXuanThang20110724** [LuongXuanThang20110724/Web_TalkDesk#9]
- [x] 1. Đặc tả chức năng đăng nhập
- [x] 2. Đặc tả chức năng đăng ký
- [x] 3. Đặc tả chức năng đăng xuất
- [x] 4. Đặc tả chức năng khôi phục mật khẩu
- [x] 5. Đặc tả chức năng tìm kiếm
- [x] 6. Đặc tả chức năng option
- [x] 7. Đặc tả chức năng liên hệ

**Comment by quyenthieucanxi** [comment]
21/03 - Hoàn thành task 1
https://docs.google.com/document/d/1V2JcIl7chCqjWtg4AoCgpLCjq0_5EBzTLtQ0FMum3oo/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
22/03 - Hoàn thành task 2
https://docs.google.com/document/d/1yOc46N39AhtJfNGqK2W_8MXaNkdfOhAhqi5z44Lmars/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
23/03 - Hoàn thành task 3
https://docs.google.com/document/d/1koxC2rziBjDY0YcELmJRS2TX1E99X7MEtCjvoMeItDo/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
24/03 - Hoàn thành task 4
https://docs.google.com/document/d/1Nhvtr-PAZALQjRIvelgLl3l4ublLkA_Gz7UIrD8H_E4/edit?usp=sharing

**Comment by quyenthieucanxi** [comment]
26/03 - Hoàn thành task 5 , task 6 và task 7
https://docs.google.com/document/d/1iGwuerFGi4zkb6KHbb03NiYQg43PdZayrQwOgebEZts/edit?usp=sharing
